import NavBar from "../../components/NavBar";

export const metadata = {
  title: {
    default: "Home | Next Movies",
    template: "%s | Next Movies",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
